---
title: "Exploratory Data Analysis"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(haven)
```

**Importing Data**

```{r}
weather_df <- 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") %>% 
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10, 
    month = floor_date(date, unit = "month")) %>% 
  select(name, id, everything())
```

**Making Plots**

```{r}
weather_df %>% 
  ggplot(aes(x = prcp)) + 
  geom_histogram()
```

```{r}
weather_df %>% 
  filter(prcp > 1000)
```


```{r}
weather_df %>% 
  filter(tmax > 20, tmax < 30) %>% 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) + 
  geom_point()
```

## Group_by()

```{r}
weather_df %>% 
  group_by(month, name)
```

**Counting**

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    n_obs = n(), 
    )
```

```{r}
weather_df %>%  
  count(name)
```


## 2x2

```{r}
weather_df %>% 
  drop_na(tmax) %>% 
  filter(name != "Molokai_HI") %>% 
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold", 
      tmax >= 5 ~ "not_cold"
    )
  ) %>% 
  group_by(name,cold) %>% 
  summarize(count = n()) 
```


```{r}
weather_df %>% 
  drop_na(tmax) %>% 
  filter(name != "Molokai_HI") %>% 
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold", 
      tmax >= 5 ~ "not_cold"
    )
  ) %>% 
  janitor::tabyl(name, cold)
```


## General Numeric Summaries

```{r}
weather_df %>% 
  group_by(name) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE), 
    median_tmin = median(tmin, na.rm = TRUE), 
    sd_prcp = sd(prcp, na.rm = TRUE)
  )
```

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE), 
    median_tmin = median(tmin, na.rm = TRUE), 
    sd_prcp = sd(prcp, na.rm = TRUE)
  )
```

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE), 
    median_tmin = median(tmin, na.rm = TRUE), 
    sd_prcp = sd(prcp, na.rm = TRUE)
  )
```

**Summarize and Plot**

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE), 
    median_tmin = median(tmin, na.rm = TRUE), 
    sd_prcp = sd(prcp, na.rm = TRUE)
  ) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
  geom_point() + 
  geom_line()
```

**Format for Readers**

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) %>% 
  pivot_wider(
    names_from = name, 
    values_from = mean_tmax
  ) %>% 
  knitr::kable(digits = 3)
```

## Grouped Mutates 

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax
    ) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) + 
  geom_point() 
```

**Find Hottest/Coldest Days** 

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    temp_rank = min_rank(desc(tmax))
  ) %>% 
  filter(temp_rank < 4)


weather_df %>% 
  group_by(name) %>% 
  filter(min_rank(tmax) < 4) %>% 
  arrange(tmax)
```

Biggest day to day temperature change

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    lagged_tmax = lag(tmax),
    temp_change = tmax - lagged_tmax
  ) %>% 
  filter(min_rank(temp_change) < 3)
```


```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    lagged_tmax = lag(tmax),
    temp_change = tmax - lagged_tmax
  ) %>% 
  summarize(
    sd_tmax_change = sd(temp_change, na.rm = TRUE)
  )
```

**Learning Checks**
```{r}
pulse_df <- 
  read_sas("data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit",
    values_to = "bdi",
    names_prefix = "bdi_score_"
  ) 
  
pulse_df %>% 
  group_by(visit) %>%  
  summarize(
    mean_bdi_visit = mean(bdi, na.rm = TRUE)
  ) %>%  
  knitr::kable(digits = 1)
```

```{r}
pups_df = 
  read_csv("./data/FAS_pups.csv", na = c("NA", ".","")) %>% 
  janitor::clean_names() 

litters_df <- 
  read_csv("data/FAS_litters.csv", na = c("NA", ".","")) %>% 
  janitor::clean_names() %>% 
  separate(group, into = c("dose", "tx_day"), 3)

fas_df <- 
  left_join(pups_df, litters_df, by = "litter_number")
```

```{r}
fas_df %>% 
  drop_na(dose) %>% 
  group_by(dose, tx_day) %>% 
  summarize(mean_pivot = mean(pd_pivot, na.rm = TRUE)) 
```

