---
title: "Visualization 2"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(patchwork)
library(haven)
```

**Importing Data**
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") %>% 
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>% 
  select(name, id, everything())
```

**Make a Scatterplot**

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.3) + 
  labs(
    title = "Temperature scatterplot", 
    x = "Minimum Temp (C)", 
    y = "Maximum Temp (C)",
    color = "Location", 
    caption = "Weather data taken from rnoaa package for three stations."
  )
```


**Scales**

- Start with `x` and `y` and then do `color`

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.3) + 
  labs(
    title = "Temperature scatterplot", 
    x = "Minimum Temp (C)", 
    y = "Maximum Temp (C)",
    color = "Location", 
    caption = "Weather data taken from rnoaa package for three stations."
  ) + 
  scale_x_continuous(
    breaks = c(-15,0,20), 
    labels = c("-15C", "0", "20")
  ) + 
  scale_y_continuous(
    limits = c(0,30), 
    transform = "sqrt"
  )
```

**Color**

`viridis` package has nice color scales 

```{r}
ggp_scatterplot <- 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.3) + 
  labs(
    title = "Temperature scatterplot", 
    x = "Minimum Temp (C)", 
    y = "Maximum Temp (C)",
    color = "Location", 
    caption = "Weather data taken from rnoaa package for three stations."
  ) + 
  viridis::scale_color_viridis(discrete = TRUE)
```

**Themes**

```{r}
ggp_scatterplot + 
  theme(legend.position = "bottom")
```

```{r}
ggp_scatterplot + 
  theme_bw() + 
  theme(legend.position = "bottom")
```

- Order Matters 

```{r}
ggp_scatterplot + 
  theme(legend.position = "bottom") + 
  theme_bw() 
```

- `Theme_bw()` resets the whole plot, so you have to put them in a specific order

```{r}
ggp_scatterplot + theme(legend.position = "bottom") + 
  theme_classic()
```

```{r}
ggp_scatterplot + theme(legend.position = "bottom") + 
  ggthemes::theme_excel()
```

**Learning Assessment**

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name, size = prcp)) + 
  geom_point(alpha = 0.3) + 
  geom_smooth(se = FALSE) +
  labs(
    title = "Seasonal Variation in Maximum Temperature",
    x = "Date", 
    y = "Maximum Temperature (C)", 
    size = "Precipitation"
  ) +
  viridis::scale_color_viridis(discrete = TRUE)  + 
  theme_minimal() +
  theme(legend.position = "bottom") 
```

**Bonus `ggplot` Features**

- Use different data sets in different `geoms` 

```{r}
central_park_df <- 
  weather_df %>% 
  filter(name == "CentralPark_NY")

molokai_df <- 
  weather_df %>% 
  filter(name == "Molokai_HI")

molokai_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point() + 
  geom_line(data = central_park_df)
```

## Multiple Panels 

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) + 
  geom_density() + 
  facet_grid(.~name)
```


```{r}
ggp_tmax_tmin <- 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.3)

ggp_tmax_density <- 
  weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) + 
  geom_density() + 
  facet_grid(.~name)

ggp_tmax_date <- 
  weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point() + 
  geom_smooth(se = FALSE)

(ggp_tmax_tmin + ggp_tmax_density) / ggp_tmax_date
```

## Data Manipulation 

```{r}
weather_df %>% 
  mutate(name = fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhold_WA"))) %>% 
  ggplot(aes(x = name, y = tmax, fill = name)) + 
  geom_violin(alpha = 0.5)
```


**Pulse Data**

```{r}
pulse_df <- 
  read_sas("data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
    ) %>% 
  mutate(visit = ifelse(visit == "bl", "00m", visit))
pulse_df %>% 
  ggplot(aes(x = visit, y = bdi_score)) + 
  geom_boxplot()
```


```{r}
pups_df <- 
  read_csv("data/FAS_pups.csv", na = c("NA", ".","")) %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    cols = pd_ears:pd_walk, 
    values_to = "pn_day", 
    names_to = "outcome",
    names_prefix = "pd_"
  )
 
litters_df <- 
  read_csv("data/FAS_litters.csv", na = c("NA", ".","")) %>% 
  janitor::clean_names() %>% 
  separate(group, into = c("dose", "tx_day"), 3)

fas_data <- 
  left_join(pups_df,litters_df, by = "litter_number") 

fas_data %>% 
  drop_na(tx_day) %>%
  ggplot(aes(x = dose, y = pn_day)) + 
  geom_boxplot() + 
  facet_grid(tx_day ~ outcome)
```

